// AUTOGENERATED BY GUNA FRAMEWORK - DO NOT EDIT MANUALLY
namespace GAME1_
{
    partial class TAOGAME_NGHECHONHINH
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TAOGAME_NGHECHONHINH));
            this.picSound = new Guna.UI2.WinForms.Guna2PictureBox();
            this.pnlMain = new Guna.UI2.WinForms.Guna2Panel();
            this.panelLuaChon3 = new Guna.UI2.WinForms.Guna2Panel();
            this.picLuaChon3 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.panelLuaChon2 = new Guna.UI2.WinForms.Guna2Panel();
            this.picLuaChon2 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.panelLuaChon1 = new Guna.UI2.WinForms.Guna2Panel();
            this.picLuaChon1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.pnlDiem = new Guna.UI2.WinForms.Guna2Panel();
            this.lblDiem = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.pnlCauHoi = new Guna.UI2.WinForms.Guna2Panel();
            this.lblCauHoi = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.lblTieuDe = new Guna.UI2.WinForms.Guna2Button();
            this.guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            ((System.ComponentModel.ISupportInitialize)(this.picSound)).BeginInit();
            this.pnlMain.SuspendLayout();
            this.panelLuaChon3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon3)).BeginInit();
            this.panelLuaChon2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon2)).BeginInit();
            this.panelLuaChon1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon1)).BeginInit();
            this.pnlDiem.SuspendLayout();
            this.pnlCauHoi.SuspendLayout();
            this.SuspendLayout();
            // 
            // picSound
            // 
            this.picSound.BackColor = System.Drawing.Color.Transparent;
            this.picSound.Image = ((System.Drawing.Image)(resources.GetObject("picSound.Image")));
            this.picSound.ImageRotate = 0F;
            this.picSound.Location = new System.Drawing.Point(24, 101);
            this.picSound.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.picSound.Name = "picSound";
            this.picSound.Size = new System.Drawing.Size(152, 165);
            this.picSound.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picSound.TabIndex = 2;
            this.picSound.TabStop = false;
            this.picSound.UseTransparentBackground = true;
            this.picSound.Click += new System.EventHandler(this.picSound_Click);
            // 
            // pnlMain
            // 
            this.pnlMain.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.pnlMain.BackColor = System.Drawing.Color.Transparent;
            this.pnlMain.BorderRadius = 25;
            this.pnlMain.Controls.Add(this.panelLuaChon3);
            this.pnlMain.Controls.Add(this.panelLuaChon2);
            this.pnlMain.Controls.Add(this.panelLuaChon1);
            this.pnlMain.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(25)))), ((int)(((byte)(101)))));
            this.pnlMain.Location = new System.Drawing.Point(180, 231);
            this.pnlMain.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(1110, 461);
            this.pnlMain.TabIndex = 3;
            // 
            // panelLuaChon3
            // 
            this.panelLuaChon3.BorderRadius = 15;
            this.panelLuaChon3.Controls.Add(this.picLuaChon3);
            this.panelLuaChon3.FillColor = System.Drawing.Color.White;
            this.panelLuaChon3.Location = new System.Drawing.Point(750, 61);
            this.panelLuaChon3.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.panelLuaChon3.Name = "panelLuaChon3";
            this.panelLuaChon3.Padding = new System.Windows.Forms.Padding(11, 12, 11, 12);
            this.panelLuaChon3.Size = new System.Drawing.Size(300, 339);
            this.panelLuaChon3.TabIndex = 2;
            // 
            // picLuaChon3
            // 
            this.picLuaChon3.BackColor = System.Drawing.Color.White;
            this.picLuaChon3.BorderRadius = 10;
            this.picLuaChon3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picLuaChon3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picLuaChon3.ImageRotate = 0F;
            this.picLuaChon3.Location = new System.Drawing.Point(11, 12);
            this.picLuaChon3.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.picLuaChon3.Name = "picLuaChon3";
            this.picLuaChon3.Size = new System.Drawing.Size(278, 315);
            this.picLuaChon3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLuaChon3.TabIndex = 0;
            this.picLuaChon3.TabStop = false;
            this.picLuaChon3.Tag = "2";
            this.picLuaChon3.Click += new System.EventHandler(this.picLuaChon_Click);
            // 
            // panelLuaChon2
            // 
            this.panelLuaChon2.BorderRadius = 15;
            this.panelLuaChon2.Controls.Add(this.picLuaChon2);
            this.panelLuaChon2.FillColor = System.Drawing.Color.White;
            this.panelLuaChon2.Location = new System.Drawing.Point(405, 61);
            this.panelLuaChon2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.panelLuaChon2.Name = "panelLuaChon2";
            this.panelLuaChon2.Padding = new System.Windows.Forms.Padding(11, 12, 11, 12);
            this.panelLuaChon2.Size = new System.Drawing.Size(300, 339);
            this.panelLuaChon2.TabIndex = 1;
            // 
            // picLuaChon2
            // 
            this.picLuaChon2.BackColor = System.Drawing.Color.White;
            this.picLuaChon2.BorderRadius = 10;
            this.picLuaChon2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picLuaChon2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picLuaChon2.ImageRotate = 0F;
            this.picLuaChon2.Location = new System.Drawing.Point(11, 12);
            this.picLuaChon2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.picLuaChon2.Name = "picLuaChon2";
            this.picLuaChon2.Size = new System.Drawing.Size(278, 315);
            this.picLuaChon2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLuaChon2.TabIndex = 0;
            this.picLuaChon2.TabStop = false;
            this.picLuaChon2.Tag = "1";
            this.picLuaChon2.Click += new System.EventHandler(this.picLuaChon_Click);
            // 
            // panelLuaChon1
            // 
            this.panelLuaChon1.BorderRadius = 15;
            this.panelLuaChon1.Controls.Add(this.picLuaChon1);
            this.panelLuaChon1.FillColor = System.Drawing.Color.White;
            this.panelLuaChon1.Location = new System.Drawing.Point(60, 61);
            this.panelLuaChon1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.panelLuaChon1.Name = "panelLuaChon1";
            this.panelLuaChon1.Padding = new System.Windows.Forms.Padding(11, 12, 11, 12);
            this.panelLuaChon1.Size = new System.Drawing.Size(300, 339);
            this.panelLuaChon1.TabIndex = 0;
            // 
            // picLuaChon1
            // 
            this.picLuaChon1.BackColor = System.Drawing.Color.White;
            this.picLuaChon1.BorderRadius = 10;
            this.picLuaChon1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picLuaChon1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picLuaChon1.ImageRotate = 0F;
            this.picLuaChon1.Location = new System.Drawing.Point(11, 12);
            this.picLuaChon1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.picLuaChon1.Name = "picLuaChon1";
            this.picLuaChon1.Size = new System.Drawing.Size(278, 315);
            this.picLuaChon1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLuaChon1.TabIndex = 0;
            this.picLuaChon1.TabStop = false;
            this.picLuaChon1.Tag = "0";
            this.picLuaChon1.Click += new System.EventHandler(this.picLuaChon_Click);
            // 
            // pnlDiem
            // 
            this.pnlDiem.BackColor = System.Drawing.Color.Transparent;
            this.pnlDiem.BorderRadius = 20;
            this.pnlDiem.Controls.Add(this.lblDiem);
            this.pnlDiem.Controls.Add(this.label1);
            this.pnlDiem.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(25)))), ((int)(((byte)(101)))));
            this.pnlDiem.Location = new System.Drawing.Point(53, 769);
            this.pnlDiem.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.pnlDiem.Name = "pnlDiem";
            this.pnlDiem.Size = new System.Drawing.Size(180, 122);
            this.pnlDiem.TabIndex = 4;
            // 
            // lblDiem
            // 
            this.lblDiem.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDiem.ForeColor = System.Drawing.Color.White;
            this.lblDiem.Location = new System.Drawing.Point(4, 54);
            this.lblDiem.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblDiem.Name = "lblDiem";
            this.lblDiem.Size = new System.Drawing.Size(171, 58);
            this.lblDiem.TabIndex = 1;
            this.lblDiem.Text = "0";
            this.lblDiem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Montserrat", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(53, 15);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(84, 38);
            this.label1.TabIndex = 0;
            this.label1.Text = "Điểm";
            // 
            // pnlCauHoi
            // 
            this.pnlCauHoi.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlCauHoi.BackColor = System.Drawing.Color.Transparent;
            this.pnlCauHoi.BorderRadius = 20;
            this.pnlCauHoi.Controls.Add(this.lblCauHoi);
            this.pnlCauHoi.Controls.Add(this.label3);
            this.pnlCauHoi.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(25)))), ((int)(((byte)(101)))));
            this.pnlCauHoi.Location = new System.Drawing.Point(1245, 769);
            this.pnlCauHoi.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.pnlCauHoi.Name = "pnlCauHoi";
            this.pnlCauHoi.Size = new System.Drawing.Size(180, 122);
            this.pnlCauHoi.TabIndex = 5;
            // 
            // lblCauHoi
            // 
            this.lblCauHoi.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCauHoi.ForeColor = System.Drawing.Color.White;
            this.lblCauHoi.Location = new System.Drawing.Point(4, 54);
            this.lblCauHoi.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCauHoi.Name = "lblCauHoi";
            this.lblCauHoi.Size = new System.Drawing.Size(171, 58);
            this.lblCauHoi.TabIndex = 1;
            this.lblCauHoi.Text = "1/20";
            this.lblCauHoi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblCauHoi.Click += new System.EventHandler(this.lblCauHoi_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Montserrat", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(60, 15);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(65, 38);
            this.label3.TabIndex = 0;
            this.label3.Text = "Câu";
            // 
            // lblTieuDe
            // 
            this.lblTieuDe.BorderRadius = 15;
            this.lblTieuDe.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.lblTieuDe.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.lblTieuDe.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.lblTieuDe.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.lblTieuDe.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(9)))), ((int)(((byte)(25)))), ((int)(((byte)(101)))));
            this.lblTieuDe.Font = new System.Drawing.Font("Montserrat", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.lblTieuDe.ForeColor = System.Drawing.Color.White;
            this.lblTieuDe.Location = new System.Drawing.Point(-39, 31);
            this.lblTieuDe.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Size = new System.Drawing.Size(375, 61);
            this.lblTieuDe.TabIndex = 7;
            this.lblTieuDe.Text = "Nghe - chọn hình";
            // 
            // guna2BorderlessForm1
            // 
            this.guna2BorderlessForm1.BorderRadius = 15;
            this.guna2BorderlessForm1.ContainerControl = this;
            this.guna2BorderlessForm1.DockIndicatorTransparencyValue = 0.6D;
            this.guna2BorderlessForm1.TransparentWhileDrag = true;
            // 
            // guna2ControlBox1
            // 
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.BackColor = System.Drawing.Color.MidnightBlue;
            this.guna2ControlBox1.FillColor = System.Drawing.Color.White;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.MidnightBlue;
            this.guna2ControlBox1.Location = new System.Drawing.Point(1419, 12);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.Size = new System.Drawing.Size(45, 29);
            this.guna2ControlBox1.TabIndex = 8;
            this.guna2ControlBox1.Click += new System.EventHandler(this.guna2ControlBox1_Click);
            // 
            // TAOGAME_NGHECHONHINH
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1476, 940);
            this.Controls.Add(this.guna2ControlBox1);
            this.Controls.Add(this.lblTieuDe);
            this.Controls.Add(this.pnlCauHoi);
            this.Controls.Add(this.pnlDiem);
            this.Controls.Add(this.pnlMain);
            this.Controls.Add(this.picSound);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "TAOGAME_NGHECHONHINH";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Game - Nghe chọn hình";
            this.Load += new System.EventHandler(this.Form2_Load);
            ((System.ComponentModel.ISupportInitialize)(this.picSound)).EndInit();
            this.pnlMain.ResumeLayout(false);
            this.panelLuaChon3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon3)).EndInit();
            this.panelLuaChon2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon2)).EndInit();
            this.panelLuaChon1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picLuaChon1)).EndInit();
            this.pnlDiem.ResumeLayout(false);
            this.pnlDiem.PerformLayout();
            this.pnlCauHoi.ResumeLayout(false);
            this.pnlCauHoi.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        // Thay thế các control cũ bằng control của Guna
        private Guna.UI2.WinForms.Guna2PictureBox picSound;
        private Guna.UI2.WinForms.Guna2Panel pnlMain;
        private Guna.UI2.WinForms.Guna2Panel panelLuaChon1;
        private Guna.UI2.WinForms.Guna2PictureBox picLuaChon1;
        private Guna.UI2.WinForms.Guna2Panel panelLuaChon3;
        private Guna.UI2.WinForms.Guna2PictureBox picLuaChon3;
        private Guna.UI2.WinForms.Guna2Panel panelLuaChon2;
        private Guna.UI2.WinForms.Guna2PictureBox picLuaChon2;
        private Guna.UI2.WinForms.Guna2Panel pnlDiem;
        private System.Windows.Forms.Label lblDiem;
        private System.Windows.Forms.Label label1;
        private Guna.UI2.WinForms.Guna2Panel pnlCauHoi;
        private System.Windows.Forms.Label lblCauHoi;
        private System.Windows.Forms.Label label3;
        private Guna.UI2.WinForms.Guna2Button lblTieuDe; // Dùng Guna2Button để thay thế Label cho dễ style
        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
    }
}